/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** NAPI object types for the AkiDB engine. */
export interface EngineOptionsJs {
  storagePath: string
  disableWal?: boolean
}
export interface CollectionJs {
  collectionId: string
  dimension: number
  metric: string
  embeddingModelId: string
  schemaVersion: string
  createdAt: string
  deletedAt?: string
  quantization: string
  hnswM: number
  hnswEfConstruction: number
  hnswEfSearch: number
}
export interface CreateCollectionOptsJs {
  collectionId: string
  dimension: number
  metric: string
  embeddingModelId: string
  /** Vector quantization: "fp16" (default) or "sq8". */
  quantization?: string
  /** HNSW M parameter (max connections per node). Default: 16, range: 4-64. */
  hnswM?: number
  /** HNSW efConstruction parameter. Default: 200, range: 50-800. */
  hnswEfConstruction?: number
  /** HNSW efSearch parameter. Default: 100, range: 10-500. */
  hnswEfSearch?: number
}
export interface RecordJs {
  chunkId: string
  docId: string
  vector: Array<number>
  metadataJson: string
  chunkText?: string
}
export interface UpsertResultJs {
  segmentIds: Array<string>
  bufferedCount: number
}
export interface SearchOptsJs {
  collectionId: string
  queryVector: Array<number>
  topK: number
  filtersJson?: string
  manifestVersion?: number
  includeUncommitted?: boolean
  /** Search mode: "vector" (default), "keyword", or "hybrid". */
  mode?: string
  /** Query text for keyword/hybrid search. */
  queryText?: string
  /** Weight for vector results in hybrid RRF fusion (default 1.0). */
  vectorWeight?: number
  /** Weight for keyword results in hybrid RRF fusion (default 1.0). */
  keywordWeight?: number
  /** When true, include per-result scoring breakdown. */
  explain?: boolean
  /** Per-query ef_search override (range: 10-500). Overrides collection default. */
  efSearch?: number
}
export interface ExplainInfoJs {
  vectorScore?: number
  bm25Score?: number
  rrfScore?: number
  vectorRank?: number
  bm25Rank?: number
  chunkPreview?: string
  matchedTerms: Array<string>
}
export interface SearchResultEngineJs {
  chunkId: string
  score: number
  committed?: boolean
  explain?: ExplainInfoJs
}
export interface SearchResponseJs {
  results: Array<SearchResultEngineJs>
  manifestVersionUsed: number
}
export interface PublishOptsJs {
  segmentIds: Array<string>
  tombstoneIds: Array<string>
  embeddingModelId: string
  pipelineSignature: string
}
export interface ManifestJs {
  manifestId: string
  collectionId: string
  version: number
  segmentIds: Array<string>
  tombstoneIds: Array<string>
  embeddingModelId: string
  pipelineSignature: string
  createdAt: string
  checksum: string
}
export interface CompactResultJs {
  recordsKept: number
  recordsRemoved: number
  spaceReclaimedBytes: number
  manifest: ManifestJs
}
/**
 * SQLite-backed file registry used by `fabric-ingest`.
 *
 * Kept as a separate N-API adapter so the main engine entrypoint stays focused
 * on collection, segment, manifest, and query operations.
 */
export declare class JobRegistryNative {
  constructor(dbPath: string)
  getFile(sourcePath: string): string | null
  upsertFile(recordJson: string): void
  deleteFile(sourcePath: string): void
  listFiles(): string
  getKnownFileStates(): string
  getKnownFingerprints(): string
  close(): void
}
/**
 * The main AkiDB engine exposed to Node.js via NAPI.
 * Thread-safe via internal subsystem locks.
 */
export declare class AkiDbEngine {
  constructor(opts: EngineOptionsJs)
  createCollection(opts: CreateCollectionOptsJs): CollectionJs
  getCollection(collectionId: string): CollectionJs | null
  listCollections(): Array<CollectionJs>
  deleteCollection(collectionId: string): void
  upsertBatch(collectionId: string, records: Array<RecordJs>): UpsertResultJs
  flushWrites(collectionId: string): Array<string>
  publish(collectionId: string, opts: PublishOptsJs): ManifestJs
  autoPublish(collectionId: string, embeddingModelId: string, pipelineSignature: string): ManifestJs
  search(opts: SearchOptsJs): SearchResponseJs
  deleteChunks(collectionId: string, chunkIds: Array<string>, reasonCode: string): number
  compact(collectionId: string): CompactResultJs
  rollback(collectionId: string, manifestId: string): ManifestJs
  getStorageSizeBytes(): number
  getTombstoneCount(collectionId: string): number
  close(): void
}
